### ISSUE TITLE
field query is the wrong type (str). Expected: unicode

### ISSUE THREAD

**Issue by husanu** [b4dnewz/node-censys#1]
running code from examples

```js
censys.search('ipv4', {query: '8.8.8.8'}, {}, (err, result) => {
  if (err) {
    console.log(err)
    return
  }

  console.log(result)
})
```

will return 

```js
{ status: 'error',
  error_type: 'malformed_request',
  error: 'field query is the wrong type (str). Expected: unicode' }
```

```sh
$ node -v
v10.14.2
```

**Comment by b4dnewz** [comment]
Thanks for pointing this out, actually I had a misconfiguration in the search function signature, I've updated it fixing the problem and also updated the documentation.

thank you so much, if the problem still persists with the new version 0.0.5 please reopen the issue
